using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext _context;

        public CustomersController()
        {

            ViewBag.Message = RoleName.USER_NAME;
            _context = new ApplicationDbContext();
        }
        // GET: Customers
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Account()
        {

            var branches = _context.Branches.ToList();
            var customers = _context.Customers.ToList();
            var loanDetails = _context.LoanDetails.ToList();
            var customerAccountTypes = _context.CustomerAccountTypes.ToList();

            var viewModel = new CustomerAccountViewModel
            {
                Branches = branches,
                Customers = customers,
                LoanDetails = loanDetails,
                CustomerAccountTypes = customerAccountTypes,
                CustomerAccount = new CustomerAccount()

            };
            return View("CustomerAccount", viewModel);
        }

        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            customer.Id = getAutoGeneratedPassword();
           
            _context.Customers.Add(customer);
            _context.SaveChanges();
            return View("Index");
        }

        [NonAction]
        public string getAutoGeneratedPassword()
        {
            var GLRanCode = RandomString(9);

            return GLRanCode;

        }
        [NonAction]
        public static string RandomString(int length)
        {
            Random random = new Random();
            const string chars = "01234567890123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}